/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blablamessenger;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gleb
 */
public class GetUserNameFrame extends javax.swing.JFrame {
 
    String name = "";
    
    /**
     * Creates new form GetUserNameFrame
     */
    public GetUserNameFrame()
    {
        super();
        initComponents();
        setVisible( true );
    }
    
    /**
     *
     * @return
     */
    public String getUserName() 
    {
        synchronized( this ) {
            try {
                wait();
            } catch (InterruptedException ex) {
                Logger.getLogger(GetUserNameFrame.class.getName()).
                        log(Level.SEVERE, null, ex);
            }
        }

        return name;
    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameArea = new javax.swing.JTextField();
        NameAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose your name");
        setName("GetUserNameFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 100));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 100));

        NameArea.setName("NameArea"); // NOI18N

        NameAccept.setText("OK");
        NameAccept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NameAccept.setName("NameAccept"); // NOI18N
        NameAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(NameAccept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121))
            .addComponent(NameArea)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameAccept)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameAcceptActionPerformed
        synchronized( this )
        {
            if ( !NameArea.getText().isEmpty() ) {
                name = NameArea.getText();
                notifyAll();
            }
        }
    }//GEN-LAST:event_NameAcceptActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NameAccept;
    private javax.swing.JTextField NameArea;
    // End of variables declaration//GEN-END:variables

}
